---
name: Release

on:
  release:
    types: [published]

jobs:

  build:
    if: ${{ github.repository }} == 'platform-application-operator'
    runs-on: [self-hosted, management-ecr]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::593291632749:role/github-actions-management-ecr
          role-duration-seconds: 1200

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: 593291632749

      - name: Set up s2i
        run: curl -L https://github.com/openshift/source-to-image/releases/download/v1.3.1/source-to-image-v1.3.1-a5a77147-linux-amd64.tar.gz | tar -xz -C /usr/bin

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test candidate image
        run: make test IMAGE_NAME=${{ steps.login-ecr.outputs.registry }}/rshiny-s2i:4.0.5-${GITHUB_REF#refs/tags/}

      - name: Build image
        run: make build IMAGE_NAME=${{ steps.login-ecr.outputs.registry }}/rshiny-s2i:4.0.5-${GITHUB_REF#refs/tags/}

      - name: Push image
        run: docker push ${{ steps.login-ecr.outputs.registry }}/rshiny-s2i:4.0.5-${GITHUB_REF#refs/tags/}
